### ISSUE TITLE
Ruby 3.4

### ISSUE THREAD

**Issue by nicolasleger** [Scalingo/ruby-buildpack#88] opened 2024-12-27 15:08 UTC
Sync with upstream so we have the new Ruby 3.4 version [`dd401008f8ff387219d6c3b00526a9aff6393ac3`](https://github.com/heroku/heroku-buildpack-ruby/pull/1531) and https://devcenter.heroku.com/articles/ruby-support-reference#ruby-versions

**Comment by EtienneM** [comment] 2024-12-27 15:25
Hi,

This will be handled as part of issue #85. Closing this issue as duplicate of #85.

**Closed by EtienneM** 2024-12-27 15:25 UTC
