### ISSUE TITLE
Add Ruby 3.4.0 support

### ISSUE THREAD

**Issue by guillaumewrobel** [Scalingo/ruby-buildpack#87] opened 2024-12-25 16:27 UTC
https://github.com/heroku/heroku-buildpack-ruby/pull/1532

@Frzk 🎁🎉

**Comment by EtienneM** [comment] 2024-12-27 07:19
This will be handled as part of the issue https://github.com/Scalingo/ruby-buildpack/issues/85. Closing this one as it's a duplicate of #85.

**Closed by EtienneM** 2024-12-27 07:19 UTC
